language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install enum34 mock; fi
  - pip install -r requirements.txt
  - travis_retry python setup.py install
  - pip install coveralls

script:
    coverage run --source=betfairlightweight setup.py test

after_success:
  coveralls

